name: Bug Report
description: File a bug so we can fix it
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and where did you see it?
      placeholder: A clear, concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: How can we reproduce the issue?
      placeholder: |
        1. Go to ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What you thought would happen.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: OS, browser/runtime, version, branch, etc.
