.PHONY: init run test

init:
	PYTHONPATH=backend python2 -c "from app import init_db; init_db()"


#Remember to change path
run:
	C:\Python27\python.exe ./backend/app.py

test: 
	PYTHONPATH=backend python2 ./backend/app_tests.py

