name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Go mod tidy
        working-directory: go_rewrite/src/backend
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          working-directory: go_rewrite/src/backend
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: ./...
          only-new-issues: false
          # Use the correct output format to avoid deprecation warning
          format: github-actions  
          # Enable caching for faster subsequent runs
          cache: true
          cache-version: v1.62.2
