name: Go Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches:

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List repository files
        run: ls -R

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      # Step 3: Install golangci-lint
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.62.2

      # Step 4: Run golangci-lint in the subdirectory
      - name: Run golangci-lint
        working-directory: whoknows_variations/whoknows_variations/go_rewrite/src/backend
        run: golangci-lint run --timeout=5m --out-format=colored-line-number
