name: Lint

on:
  pull_request:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Go mod tidy
        working-directory: go_rewrite/src/backend
        run: go mod tidy

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          working-directory: go_rewrite/src/backend
          github-token: ${{ secrets.GITHUB_TOKEN }}
          args: ./...


