name: Go Lint

on:
  push:
    branches: [ main ]
  pull_request: 

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Optional debug step
      - name: List repository files
        run: ls -R

      # Step 2: Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.0'

      # Step 3: Run golangci-lint with annotations
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: go_rewrite/src/backend
          version: v2.5.0
          fail-on-error: true
