name: Lint

on:
  pull_request:
  push:

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'

      - name: Verify Go files
        working-directory: go_rewrite/src/backend
        run: |
          go version
          ls -la
          go list ./...

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          working-directory: go_rewrite/src/backend
          args: ./...
