name: Go Lint

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  golangci-lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go_rewrite/src/backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.62.2
          working-directory: go_rewrite/src/backend
